spring:
  # Datasource configuration
  # h2 server
  h2:
    console: localhost:8080/h2-console
    enabled: true

  datasource:
    #url: jdbc:h2:tcp://localhost/./data/gestokdb
    url: jdbc:h2:file:/app/data/gestokdb.h2.db
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# Server configuration
server:
  port: 8080
  servlet:
    context-path:

# Mail configuration
mail:
  host: smtp.devmail.com
  port: 587
  username: dev_user
  password: dev_password
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG
        security: DEBUG
    com:
      gestok:
        controller: DEBUG
        service: DEBUG
        repository: DEBUG
        model: DEBUG
        security: DEBUG