name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true -B package --file pom.xml # Exécutez les tests par défaut
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar # Ou *.war selon votre projet

